import type { Metadata } from "next";
import { Plus_Jakarta_Sans } from "next/font/google";
import "./globals.scss";
import ThemeProvider from "@/context/themectx";
import Nav from "@/components/nav";
import SkeletonNavbar from "@/components/skeltonav";
import { Suspense } from "react";
import { usePathname } from "next/navigation";
import SideBar from "@/components/SideBar";
import StateCtxProvider from "@/context/statectx";

const plusJ = Plus_Jakarta_Sans({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-plus-jakarta-sans",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <StateCtxProvider>
        <ThemeProvider>
          <body
            className={`${plusJ.className}  bg-background-100 dark:bg-background-900`}
          >
            <section className="flex h-full w-full">
              <SideBar />
              <div className="md:ml-[80px] ml-[60px]">
                <Suspense fallback={<SkeletonNavbar />}>
                  <Nav brandText={""} />
                </Suspense>
                {children}
              </div>
            </section>
          </body>
        </ThemeProvider>
      </StateCtxProvider>
    </html>
  );
}
